# Generated by Django 4.1.6 on 2023-02-14 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="bithdate",
            new_name="birthdate",
        ),
    ]
